sql CREATE DATABASE IF NOT EXISTS bookdb; USE bookdb; 
CREATE TABLE IF NOT EXISTS books ( id BIGINT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
author VARCHAR(255) NOT NULL, 
category VARCHAR(255), price DOUBLE NOT NULL, available BOOLEAN NOT NULL );